### ISSUE TITLE
1.19 backport

### ISSUE THREAD

**Issue by JeremyStarTM** [mrmrmystery/Boiler#1]
It would be nice to run Boiler on a 1.19.4 server.

**Comment by mrmrmystery** [comment]
I'm focusing on the current Minecraft version and won't be creating backports for older versions. Just update to 1.20, most of your other plugins would probably still work. I hope you understand me.

**Comment by JeremyStarTM** [comment]
I can understand that (as a developer myself), but "just update to 1.20" is far easier said than done.
