### ISSUE TITLE
Plasmo Voice support

### ISSUE THREAD

**Issue by NONPLAYT** [mrmrmystery/Boiler#2]
I would like to see support for plasmo voice in the plugin. I prefer this mod instead of simple voice chat

**Comment by NONPLAYT** [comment]
and for exmaple: add two versions of plugin that support SVC or PV

**Comment by mrmrmystery** [comment]
I originally planned using plasmovoice but plasmovoice currently has a bug in their mod that throws an exception on your client when you try to play anything. If they can get this fixed I will try to implement pv support.

**Comment by NONPLAYT** [comment]
i'm looking forward to it

**Comment by NONPLAYT** [comment]
> I originally planned using plasmovoice but plasmovoice currently has a bug in their mod that throws an exception on your client when you try to play anything. If they can get this fixed I will try to implement pv support.

I wanted to ask, did you report this error to the developers of pv?

**Comment by mrmrmystery** [comment]
I told them on discord. They said they are already working on it.

**Comment by NONPLAYT** [comment]
> I originally planned using plasmovoice but plasmovoice currently has a bug in their mod that throws an exception on your client when you try to play anything. If they can get this fixed I will try to implement pv support.

i just saw that on plasmo voice wiki information about api. here it is: https://plasmovoice.com/docs/api/
Maybe trying using api with mapengine it will be possible to add pv support?

**Comment by mrmrmystery** [comment]
Added plasmovoice support in 2.0.11 https://modrinth.com/plugin/boiler/version/2.0.11

**Comment by mrmrmystery** [comment]
forgot to mentio: currently you need the prerelease version of plasmovoice. You can get it here https://github.com/plasmoapp/plasmo-voice/releases/tag/2.1.0-SNAPSHOT

**Comment by mrmrmystery** [comment]
Thats not an issue with plasmo or boiler. Seems like the api I use for getting the twitch streams is currently down. You could retrieve the m3u8 stream yourself and play it back using ffmpeg-buffered.

**Comment by mrmrmystery** [comment]
can you provide any logs or screenshots I could work with? Maybe also try restarting your server.
