### ISSUE TITLE
Displays when switching from dimensions

### ISSUE THREAD

**Issue by JustAntosha** [mrmrmystery/Boiler#3]
When players visit the Nether or The End, the displays vanish. 
The problem can be resolved by relogging; however, in certain cases, only rebooting the server proves effective. 
Can a refresh command be implemented to address this issue?

_P. S. Sorry for my English. I'm using Chat-GPT for it._

**Comment by mrmrmystery** [comment]
Should be fixed in the new version 👍 
https://modrinth.com/plugin/boiler/version/1.2.2
